### PR TITLE
Structure for pip

### PR DESCRIPTION
**Pull request by jmartin-tech**
refactor the repository to build a pip installable module we may publish to PyPI :-)

### CODE REVIEW

**Comment by jmartin-tech** [comment]
Note this changes how this code is consumed as

```
import vm_automation
```

will now make esxiServer, esxiVm, workstationServer, & workstationVm available as classes without individual imports

**Comment by bwatters-r7** [comment]
What are the test steps?

**Comment by jmartin-tech** [comment]
@bwatters-r7, sorry `pip install .` in a python env and `import vm_automation` to run the same tests available from your Readme

**Comment by bwatters-r7** [comment]
# Release Notes
This converts the vm-automation package to a pip-installable package

**Pull request merged**
